# Generated by Django 5.0.6 on 2024-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='unique_Id',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
